apiVersion: v1
kind: Secret
metadata:
  name: vmanage-config
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
type: Opaque
stringData:
  vmanage-config.yaml: |
    {{- toYaml $.Values.vmanageConfig | nindent 6 }}
