---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdwan-operator
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdwan-operator-role
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - sdwan-operator.io
  resources:
  - operators
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sdwan-operator.io
  resources:
  - operators/finalizers
  - operators/status
  verbs:
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sdwan-operator
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sdwan-operator-role
subjects:
- kind: ServiceAccount
  name: sdwan-operator
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdwan-operator-rolebinding
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sdwan-operator-role
subjects:
- kind: ServiceAccount
  name: sdwan-operator
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
