name: Linter

on:
  workflow_dispatch:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 5m
